=== iTsluku/data-on-the-web/project/sports.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/hmustafademir/data-on-the-web/blob/master/sports.schema.json",
    "title": "Sports",
    "description": "List of sport events.",
    "type": "array",
    "items": {
        "type": "object",
        "description": "Event.",
        "properties": {
            "ID": {
                "type": "integer",
                "description": "The unique event code."
            },
            "location": {
                "type": "object",
                "description": "The location description.",
                "properties": {
                    "city": {
                        "type": "object",
                        "description": "City.",
                        "properties": {
                            "ID": {
                                "type": "integer",
                                "description": "The unique city code."
                            },
                            "name": {
                                "type": "string",
                                "description": "The city name."
                            }
                        }
                    },
                    "postcode": {
                        "type": "integer",
                        "description": "The city postcode."
                    },
                    "street": {
                        "type": "string",
                        "description": "The street name."
                    },
                    "street_number": {
                        "type": "integer",
                        "description": "The street number."
                    }
                }
            },
            "date": {
                "type": "object",
                "description": "The date description.",
                "properties": {
                    "date": {
                        "type": "string",
                        "format": "date",
                        "description": "The date of the event."
                    },
                    "dateTime_start": {
                        "type": "string",
                        "format": "date-time",
                        "description": "The exact start date of the event."
                    },
                    "dateTime_end": {
                        "type": "string",
                        "format": "date-time",
                        "description": "The exact end date of the event."
                    }
                }
            },
            "title": {
                "type": "string",
                "description": "The title of the event."
            },
            "type": {
                "type": "string",
                "description": "The sport type of the event."
            },
            "description": {
                "type": "string",
                "description": "The event description."
            }
        },
        "required": [
            "ID"
        ]
    }
}

=== iTsluku/data-on-the-web/project/sports.json
[
    {
        "ID": 1,
        "location": {
            "city": {
                "ID": 3,
                "name": "Regensburg"
            },
            "postcode": 93053,
            "street": "Franz-Josef-Strau√ü-Allee",
            "street_number": 22
        },
        "date": {
            "date": "2022-09-16",
            "dateTime_start": "2022-09-16T09:00:00"
        },
        "title": "RedCon 2022",
        "type": "football",
        "description": "RedCon is Europe's largest professional development event for football coaches and is already taking place for the 3rd time. With our format we strengthen the teams behind the teams. For an even better structure, knowledge exchange and discussions at the highest level."
    },
    {
        "ID": 2,
        "location": {
            "city": {
                "ID": 4,
                "name": "Berlin"
            },
            "postcode": 15366,
            "street": "Rennbahnallee"
        },
        "date": {
            "date": "2023-04-09",
            "dateTime_start": "2023-04-09T10:30:00"
        },
        "title": "Horse racing in Hoppegarten 2023",
        "type": "horse_racing",
        "description": "Horse racing in Hoppegarten means: fast thoroughbreds, pure betting fun and excitement and in addition simply a great day in the green!"
    },
    {
        "ID": 3,
        "location": {
            "city": {
                "ID": 4,
                "name": "Berlin"
            },
            "postcode": 14053,
            "street": "Olympischer Platz",
            "street_number": 3
        },
        "date": {
            "date": "2022-11-05"
        },
        "title": "Bundesliga 2022/2023 - 13. Spieltag - Herta vs. Bayern",
        "type": "soccer"
    }
]
