=== iTsluku/data-on-the-web/lectures/04_formats_json/airport.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/martinnec/course-data-on-the-web/main/lectures/04_formats_json/airport.schema.json",
    "title": "Airport",
    "description": "An airport from the database of international civil airports.",
    "type": "object",
    "properties": {
        "code": {
            "$ref": "#/$defs/code"
        },
        "name": {
            "$ref": "#/$defs/name"
        },
        "employment": {
            "type": "array",
            "description": "The yearly statistics of the number of employees.",
            "items": {
                "type": "object",
                "description": "The employment statistics measuring the number of employees on the last day of the given year.",
                "properties": {
                    "year": {
                        "type": "string",
                        "description": "The year of the measurement."
                    },
                    "value": {
                        "type": "integer",
                        "description": "The measured value.",
                        "exclusiveMinimum": 0
                    }
                },
                "required": ["year","value"]
            },
            "minItems": 2
        },
        "departures": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "number": {
                        "$ref": "#/$defs/number"
                    },
                    "time": {
                        "$ref": "#/$defs/time",
                        "title": "actual departure time",
                        "description": "The actual time of the flight departure."
                    },
                    "to": {
                        "$ref": "#/$defs/airport-base",
                        "description": "The target destination airport of the flight."
                    }
                },
                "required": ["number"]
            }
        },
        "arrivals": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "number": {
                        "$ref": "#/$defs/number"
                    },
                    "time": {
                        "$ref": "#/$defs/time",
                        "title": "actual arrival time",
                        "description": "The actual time of the flight arrival."
                    },
                    "from": {
                        "$ref": "#/$defs/airport-base",
                        "description": "The origin airport of the flight."
                    }
                },
                "required": ["number"]
            }
        }
    },
    "required": ["code"],
    "$defs": {
        "code": {
            "type": "string",
            "title": "IATA code",
            "description": "The unique international IATA 3-letter code of the airport.",
            "minLength": 3,
            "maxLength": 3
        },
        "name": {
            "type": "string",
            "title": "name",
            "description": "The official name of the airport in english."
        },
        "number": {
            "type": "string",
            "description": "The unique number (code) that an airline assigns to the flight in its network."
        },
        "time": {
            "type": "string",
            "format": "date-time"
        },
        "airport-base": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/$defs/code"
                },
                "name": {
                    "$ref": "#/$defs/name"
                }
            }
        }
    }
}

=== iTsluku/data-on-the-web/lectures/04_formats_json/airport.json
{
    "code": "PRG",
    "name": "VÃ¡clav Havel Airport Prague",
    "employment": [{
        "year": "2019",
        "value": 2925
    },{
        "year": "2020",
        "value": 2345
    },{
        "year": "2021",
        "value": 1745
    }],
    "departures": [{
        "number": "XY1234",
        "time": "2022-07-07T15:40:00",
        "to": {
            "code": "DUB",
            "name": "Dublin Airport"
        }
    },{
        "number": "YZ8745",
        "to": {
            "code": "DUB",
            "name": "Dublin Airport"
        }
    }],
    "arrivals": [{
        "number": "AB9874",
        "time": "2022-07-07T12:14:00",
        "from": {
            "code": "DUB",
            "name": "Dublin Airport"
        }
    }]
}
